### ISSUE TITLE
field for mobile and desktop/tablet instruction in the json

### ISSUE THREAD

**Issue by tomallpress** [adaptlearning/adapt-contrib-narrative#100]
would it be possible to have two instruction fields in the json that switch out depending on which device you're looking at it on: one for desktop/tablet where the narrative works in the same way, and one for mobile where there is more instruction required to do with hitting the plus button to read the content.

at the moment we have to do this through css, using span tags in the body or instruction fields.

**Comment by zenduo** [comment]
Closed as this has been moved to https://adaptlearning.atlassian.net/browse/ABU-357
