### ISSUE TITLE
Completion not working correctly (in dev branch)

### ISSUE THREAD

**Issue by zenduo** [adaptlearning/adapt-contrib-narrative#108]
When building a dev branch of the framework, with the dev components installed too, navigate to:

http://localhost:9001/#/id/co-05

Scroll to the Narrative "What’s coming next?" block

Click the narrative arrows, until you reach the end or the narrative, notice the block doesn't complete and the progress bar doesn't go up. Clicking the narrative back arrow, the block then completes.

This causes issues for people using trickle and page-level-progress.

Tested on various browsers and issue is on all.

**Comment by hrajotia** [comment]
I think this issue came from last [PR](http://github.com/adaptlearning/adapt-contrib-narrative/pull/105) where [this if](http://github.com/adaptlearning/adapt-contrib-narrative/pull/105/files#diff-174959bd9c532c070666407a1f6eeb6bL172) statement been removed.

so we need to ask @dancgray if its removed purposefully for accessibility or we could put it back!

**Comment by dancgray** [comment]
We want to call accessibility focus at this point so I would suggest something along the lines of:

        setStage: function(stage, initial) {
            this.model.set('_stage', stage);

            if (this.model.get('_isDesktop')) {
                // Set the visited attribute for large screen devices
                var currentItem = this.getCurrentItem(stage);
                currentItem.visited = true;
            }

            this.$('.narrative-progress').removeClass('selected').eq(stage).addClass('selected');
            this.$('.narrative-slider-graphic').children('.controls').a11y_cntrl_enabled(false);
            this.$('.narrative-slider-graphic').eq(stage).children('.controls').a11y_cntrl_enabled(true);
            this.$('.narrative-content-item').addClass('narrative-hidden').a11y_on(false).eq(stage).removeClass('narrative-hidden').a11y_on(true);
            this.$('.narrative-strapline-title').a11y_cntrl_enabled(false).eq(stage).a11y_cntrl_enabled(true);

            this.evaluateNavigation();
            this.evaluateCompletion();

            this.moveSliderToIndex(stage, !initial, _.bind(function() {
                if (this.model.get('_isDesktop')) {
                    this.$('.narrative-content-item').eq(stage).a11y_focus();
                } else {
                    this.$('.narrative-popup-open').a11y_focus();
                }
            }, this));

        },

I'll issue a new PR if this seems OK?

**Comment by hrajotia** [comment]
+1 looks good to me...

**Comment by oliverfoster** [comment]
+1

**Comment by zenduo** [comment]
Just tested, works for me.. +1
