### ISSUE TITLE
Allow aria of next/back buttons to be configurable

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-narrative#227]

**Comment by joe-replin** [comment]
@oliverfoster, I think this one may be eligible for closing. course.json already has a fairly flexible labelling template.

`"previous": "{{#if title}}Back to {{{title}}} (item {{itemNumber}} of {{totalItems}}){{else}}{{_globals._accessibility._ariaLabels.previous}}{{/if}}",
        "next": "{{#if title}}Forward to {{{title}}} (item {{itemNumber}} of {{totalItems}}){{else}}{{_globals._accessibility._ariaLabels.next}}{{/if}}"`

**Comment by oliverfoster** [comment]
Thanks for checking @joe-replin
