### ISSUE TITLE
adapt-contrib-narrative: minor navigation issue on NVDA

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt-contrib-narrative#236]
When you have previously selected the next button, after reading through the content as normal when you are faced with the option to select the controls again the screenreader announces 'button back, button next' if enter is selected back is selected. If you use arrow keys to potentially navigate to one of the buttons you are moved onto the next component. It is only when you use tab can you define which navigation button you want to select. To my understanding tab is not normally used as standard for screenreader users.

### Your environment
* 0.8.1 AT & 4.2.0 FW
* IE11
* Windows 10
* Narrative 5.0.1

### Steps to reproduce
Navigate through a narrative component with NVDA on IE11.

**Comment by joe-allen-89** [comment]
Able to replicate in ie11 with the latest versions (narrative v7.2.1, Fw 5.22.1) not an issue in Chrome/Edge

**Comment by oliverfoster** [comment]
possibly fixed by https://github.com/adaptlearning/adapt-contrib-narrative/pull/232#issuecomment-1200976313
