### ISSUE TITLE
Label focus after selection

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt-contrib-narrative#261]
### Subject of the issue/enhancement/features
When using JAWS or NVDA after activating the forward or back button in the narrative component, the slide is changed and focus can be visually seen landing on the heading of the new slide. However, the first piece of information announced after activation is the label of the forward button instead of the new slide heading. 

For example, if I am viewing narrative item 1 and move forward to narrative item 2, NVDA announces, "Forward to narrative item 3 (item 3 of 3), Narrative item 2". This is before if eventually announced the item heading.

If I am viewing narrative item 2 and move forward to narrative item 3, JAWS announces the trickle aria-label. 

For example, if I am viewing narrative item 2 and move back to narrative item 1, JAWS announces, "Forward to narrative item 3 (item 3 of 3), Narrative item 2". This is before if eventually announced the item heading.

### Your environment
* FW v 5.30.3
* Narrative v7.4.5
* Firefox
* Jaws 2023 & NVDA
* Windows

### Expected behaviour
Ensure that when users move between slides of the narrative component, that navigation buttons are not being announced unless they receive focus.

### Actual behaviour
The headings are being focused but the navigation buttons are being read aloud.

**Comment by oliverfoster** [comment]
That sounds exactly like the behaviour of narrative before this pr https://github.com/adaptlearning/adapt-contrib-narrative/pull/259/files

**Comment by oliverfoster** [comment]
It'll be because the element isn't "readable" at the point of focusing.
https://github.com/adaptlearning/adapt-contrib-core/blob/c54cffec551a2311ab22c60b87a0a80274bf6aaa/js/a11y.js#L709
