### ISSUE TITLE
Alternate layout option for mobile

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-narrative#267]
### Subject of the enhancement
The current mobile "strapline" experience for Narrative isn't great. It requires too much interaction and can require repeatedly scrolling up and down to ensure content is in view. I would like to explore options for creating an alternative mobile experience. This could be as simple as stacking the images and text vertically on mobile. The existing strapline layout could be preserved, but a configurable option can be added to allow switching to the new layout.

Some thoughts from our team:

- The strapline layout hides content from the learner, which is often missed.
- The plus sign layout and arrow functionality is easy to miss on mobile, which frustrates learners because they can't clearly see what needs to be interacted with and completed.
- The strapline layout doubles the number of clicks for the learner.
- A stacked layout would allow learners to always clearly see the content with zero clicks, lessening the time it takes to get through the content and eliminating the frustration caused by the interaction.

### Current mobile strapline layout

<img width="366" alt="Screenshot 2023-06-14 at 10 46 09 AM" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/898168/5ac93630-9e22-47c2-b2bf-72de29bab76b">

**Comment by oliverfoster** [comment]
Have you tried `_isMobileTextBelowImage`?

**Comment by swashbuck** [comment]
The `_isMobileTextBelowImage` option isn't terrible. However, it can still result in some up and down scrolling depending on the device size and amount of text content. Stacking the image and text would only require scrolling in one direction and no button tapping.

<img width="371" alt="_isMobileTextBelowImage" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/898168/8cb5792b-e7fc-4212-bf02-03fb5623db65">

**Comment by oliverfoster** [comment]
Excellent, can't wait to see it.

**Comment by kirsty-hames** [comment]
I tend to default to `_isMobileTextBelowImage` as this is a much better experience than the default mobile layout but I think @swashbuck's suggestion of removing all interaction and stacking image/text is another good alternative. In addition to the layout, do you think a separate mobile image would be useful should you want to provide a mobile image at a different aspect ratio to desktop e.g. letterbox?

**Comment by swashbuck** [comment]
@kirsty-hames I like the idea of allowing for a separate mobile image. Something like:

```
"_graphic": {
    "alt": "",
    "longdescription": "",
    "large": "course/en/images/narrative-lg.jpg",
    "small": "course/en/images/narrative-sm.jpg",
},
```
