### ISSUE TITLE
_isMobileTextBelowImage back button issue

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-narrative#271]
### Subject of the issue
When viewing on mobile with `_isMobileTextBelowImage` set to 'true'

- The Back button is always disabled
- The Next button is not disabled when reaching the last item.

Possibly related to https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/278

<img width="369" alt="back-disabled" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/898168/facf0554-9339-40e1-badd-c83f1a2b2f5f">

### Your environment
* Framework 5.31.12
* Narrative 7.4.9

### Steps to reproduce
1. On a Narrative, use `_isMobileTextBelowImage: true`
2. View Narrative on a mobile device or at a mobile screen width with a non-mobile device.
3. Click the Next button to go to item 2

### Expected behaviour
Once item 2 is active, the Back button should be enabled.

### Actual behaviour
Back button is not enabled.

**Comment by kirsty-hames** [comment]
I can replicate the issue described but I think it's specific to instances where the item (image and text) is greater than the screen height. For example, I can replicate this on my iPhone SE but not on an iPhone XR. I can avoid the issue on iPhone SE if I scroll each item into view before selecting the 'next' button.

**Comment by swashbuck** [comment]
> I can replicate the issue described but I think it's specific to instances where the item (image and text) is greater than the screen height. For example, I can replicate this on my iPhone SE but not on an iPhone XR. I can avoid the issue on iPhone SE if I scroll each item into view before selecting the 'next' button.

That's odd. I wasn't able to reproduce the issue based on the heights. That said, I think I've fixed it now :)
