### ISSUE TITLE
Visual item states rely on color alone

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt-contrib-narrative#288]
### Subject of the issue
Visual progress of items is represented via `.narrative__progress`, see screenshot below for progress dots below image. Item states include default, selected and visited. The change in state is represented by color change only (see [plugin](https://github.com/adaptlearning/adapt-contrib-narrative/blob/3c15d3e39debdc557dc81332edcbf25a6b561333/less/narrative.less#L163) and [Vanilla](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/cb5fc98607b042487566bab99daf4c784f5f2afd/less/plugins/adapt-contrib-narrative/narrative.less#L22) styles). This information will be difficult or impossible to perceive for individuals with visual disabilities such as low vision or color blindness. 
<img width="957" alt="narrative" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/8e2ea98b-4ae4-4c80-b08d-0e676971765a">

### Expected behaviour
Provide a non-color dependent means of identifying current item (selected) and completed items. Some ideas below but please input with any thoughts or suggestions.

**Selected state:**
Increase the size of the progress item when selected. 
<img width="120" alt="progress_selected" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/1b2cf1bc-1fa1-4c34-8d4d-c00176a1a71f">

**Completed state:**
Other presentation components display a tick icon for completed items, see screenshots below. Could do similar and display the completion tick within the progress item or as a separate icon over the Narrative image.

<img width="290" alt="hotgraphic" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/b94400a2-7436-4965-84ac-5a0624272f3e">
<img width="255" alt="accordion" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/089fa37e-37b3-4351-9c34-7de0ab8a11a4">

**Comment by kirsty-hames** [comment]
What are peoples thoughts on the following suggestions?

**1. Indicators remain small until visited**

<img width="897" alt="progress_small_1" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/86a28469-caf2-4961-aeaa-121b8224568d">
<img width="893" alt="progress_small_2" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/455ede96-70ea-43fa-8e95-0de2ae350cc4">

**2. Keep indicators size uniform**
<img width="869" alt="progress_uniform_1" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/37a03fca-0383-47e8-bdbc-8873347d84da">
<img width="844" alt="progress_uniform_2" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/451129a1-c6e7-41b6-913c-bbefcfbc231a">

Both options display a tick when visited and invert their colours when selected. The tick is displayed at `@icon-size` (1.5rem) for consistency with other component item visited ticks. This does mean that the indicators are larger than they currently are.

**Comment by oliverfoster** [comment]
I quite like 2, I'm mildly worried about having too many items and what the indicators would do. Do you have thoughts?

**Comment by kirsty-hames** [comment]
> I quite like 2, I'm mildly worried about having too many items and what the indicators would do. Do you have thoughts?

See below for how the various layouts look with 10 items without any additional styling. `"_hasNavigationInTextArea": true` needs some consideration otherwise the indicators just wrap for standard layout.

**Desktop view:**
<img width="331" alt="desktop" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/a9652360-7d48-4717-824e-b7f40a43497d">

**Medium breakpoint before single column stack:**
<img width="707" alt="before_breakpoint" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/4c1fe492-4f33-41ea-9a16-303507760c72">

**Mobile view:**
<img width="386" alt="mobile" src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/7045330/8e67507b-b3c6-47c4-ac22-5f9fc13d6fa6">

**Comment by oliverfoster** [comment]
Is it best to keep the indicators below the image always, rather moving them with the navigation buttons?

**Comment by StuartNicholls** [comment]
> Is it best to keep the indicators below the image always, rather moving them with the navigation buttons?

This actually gets requested a fair bit, so yeah, let's change it.

**Comment by StuartNicholls** [comment]
I prefer the smaller check marks, too
