### ISSUE TITLE
Revert item titles to optional

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-narrative#308]
### Subject of the issue
In #298 , item titles were made [required](https://github.com/adaptlearning/adapt-contrib-narrative/blob/d26d6682666acabe1ada182c1db8cb65a96fbcb5/properties.schema#L118) so that mobile dialogs will have an accessible title. With this change, though, learning designers no longer have the option to only include body text for items. Furthermore, in framework projects, we often use one of the mobile Narrative options that does _not_ use a dialog popup (e.g. `_isMobileTextBelowImage` or `_isStackedOnMobile`).

I would propose that we revert the `_items` `title` fields to be optional. Then, we can create a fallback value to use for the dialog title when a Narrative is configured to use the strapline layout.

### Your environment
* AAT
* Narrative 7.9.1

### Screenshots
**Mobile strapline layout**
<img src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/898168/06d47401-b919-49a8-9509-b44b81f29497" width="400">

**Mobile strapline layout when dialog is displayed**
<img src="https://github.com/adaptlearning/adapt-contrib-narrative/assets/898168/1f07c995-9c05-441d-b561-a7f0759246ae" width="400">

**Comment by oliverfoster** [comment]
> I would propose that we revert this field to be optional.

Which field?

**Comment by swashbuck** [comment]
@oliverfoster The `title` field for `_items`. I've updated the description above.

**Comment by kirsty-hames** [comment]
> I would propose that we revert the `_items` `title` fields to be optional. Then, we can create a fallback value to use for the dialog title when a Narrative is configured to use the strapline layout.

This sounds good to me @swashbuck.  I suppose something generic like "Item 1, Item 2 etc.." would be sufficient or did you have anything in mind?

**Comment by swashbuck** [comment]
@kirsty-hames Yep, I think something simple like "Item 1" would work. There is also the possibility of falling back to the `strapline` title if it exists. So, the dialog title precedence could go like:

- `_items` `title`
- `_items` `strapline`
- Generic fallback title

**Comment by oliverfoster** [comment]
Generic fallback title needs to be translatable, like:

 [`course.json:_globals._components._hotgraphic.item = "Item {{itemNumber}} of {{totalItems}}"`](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/a9c0197812b26c13978f25d7bcb956974e9c5e3f/schema/course.schema.json#L36)
